version: "3.8"

services:
  app:
    build:
      context: .
      target: tests

    stop_signal: SIGINT

    command:
      - pipenv
      - run
      - tests  # pipenv script

    depends_on:
      - mongo

    env_file:
      - .env.tests

  mongo:
    image: mongo:4.2-bionic
