version: "3.8"

services:
  app:
    build:
      dockerfile: Dockerfile.tests
      context: .

    stop_signal: SIGINT

    depends_on:
      - mongo

    environment:
      - APP_HOST=127.0.0.1
      - APP_PORT=8000
      - APP_RELOAD=0
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=TEST

  mongo:
    image: mongo:4.2-bionic
